Specify node version
With node23 I see below error

```
SyntaxError: The requested module 'resolve-pkg-maps' does not provide an export named 'resolveExports'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:181:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:264:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:583:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:93:9)

Node.js v23.7.0
```